FROM python:3.8-buster
RUN apt-get update && apt-get install -y \
    curl \
    && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
ENV PATH="${PATH}:/root/.poetry/bin" APP_PORT=5000
EXPOSE ${APP_PORT}
COPY . .
RUN chmod +x ./run_dev.sh \
    && poetry install
ENTRYPOINT ["./run_dev.sh"]